--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.13.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/13/2021 2:53:22 PM
-- Server version: 5.5.5-10.4.11-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE single_product_shop;

--
-- Definition for table orders
--
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  recipient VARCHAR(100) NOT NULL,
  address_line_1 VARCHAR(100) NOT NULL,
  address_line_2 VARCHAR(100) NOT NULL,
  admin_area_2 VARCHAR(100) NOT NULL,
  admin_area_1 VARCHAR(100) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  country_code CHAR(2) NOT NULL,
  quantity INT(11) NOT NULL,
  price DOUBLE(8, 2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table payments
--
DROP TABLE IF EXISTS payments;
CREATE TABLE payments (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT(20) UNSIGNED NOT NULL,
  paypal_transaction_id VARCHAR(255) NOT NULL,
  amount DOUBLE(8, 2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT payments_order_id_foreign FOREIGN KEY (order_id)
    REFERENCES orders(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;